import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

from idrive_backup_helper.browser.downloads import (
    download_current_folder,
    retry_missing_files_from_manifest,
    verify_download_manifest,
)
from idrive_backup_helper.browser.session import (
    DEFAULT_BROWSE_URL,
    login_and_save_state,
    open_authenticated_browser,
)
from idrive_backup_helper.filesystem.paths import (
    browser_profile_dir,
    downloads_dir,
    find_repo_root,
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="IDrive backup helper")
    subparsers = parser.add_subparsers(dest="command", required=True)

    auth_parser = subparsers.add_parser(
        "auth", help="Open a headed browser and cache IDrive login state"
    )
    auth_parser.add_argument(
        "--url",
        default="https://www.idrive.com/idrive/login/loginForm",
        help="IDrive URL to open for login",
    )

    browse_parser = subparsers.add_parser(
        "browse",
        help="Open an authenticated IDrive browser for manual folder inspection",
    )
    browse_parser.add_argument(
        "--url",
        default=DEFAULT_BROWSE_URL,
        help="IDrive URL to open in the authenticated browser",
    )

    download_parser = subparsers.add_parser(
        "download-folder",
        help="List visible files in one IDrive web folder (download step pending)",
    )
    download_parser.add_argument("--url", required=True, help="IDrive folder URL")
    download_parser.add_argument(
        "--to",
        required=True,
        type=Path,
        help="Local destination directory for downloaded files",
    )
    download_parser.add_argument(
        "--headed",
        action="store_true",
        help="Run browser in headed mode for debugging",
    )
    download_parser.add_argument(
        "--timeout-ms",
        type=int,
        default=120_000,
        help="Playwright timeout for page operations",
    )
    download_parser.add_argument(
        "--cooldown-ms",
        type=int,
        default=1_500,
        help="Pause between file download interactions",
    )
    download_parser.add_argument(
        "--overwrite",
        choices=["skip", "replace", "fail"],
        default="skip",
        help="How to handle already-existing destination files",
    )

    verify_parser = subparsers.add_parser(
        "verify-manifest",
        help="Verify which files from a download manifest are still missing locally",
    )
    verify_parser.add_argument("--manifest", required=True, type=Path)

    retry_parser = subparsers.add_parser(
        "retry-manifest",
        help="Retry only missing files from a manifest generated by download-folder",
    )
    retry_parser.add_argument("--manifest", required=True, type=Path)
    retry_parser.add_argument("--headed", action="store_true")
    retry_parser.add_argument("--timeout-ms", type=int, default=120_000)
    retry_parser.add_argument("--cooldown-ms", type=int, default=1_500)
    retry_parser.add_argument(
        "--overwrite",
        choices=["skip", "replace", "fail"],
        default="replace",
    )

    return parser


def _run_auth(url: str) -> None:
    repo_root = find_repo_root()
    profile_dir = browser_profile_dir(repo_root)
    login_and_save_state(profile_dir=profile_dir, start_url=url)

    print(f"Saved browser state under: {profile_dir}")
    print(
        "Next step: uv run main browse or uv run main download-folder --url <FOLDER_URL> --to <DEST_PATH>"
    )


def _run_browse(url: str) -> None:
    repo_root = find_repo_root()
    profile_dir = browser_profile_dir(repo_root)
    open_authenticated_browser(profile_dir=profile_dir, start_url=url)


def _run_download_folder(
    *,
    url: str,
    destination: Path,
    headed: bool,
    timeout_ms: int,
    cooldown_ms: int,
    overwrite: str,
) -> int:
    repo_root = find_repo_root()
    profile_dir = browser_profile_dir(repo_root)

    if not profile_dir.exists():
        raise RuntimeError("Missing browser auth state. Run: uv run main auth")

    staged_downloads_dir = downloads_dir(repo_root)
    report = download_current_folder(
        profile_dir=profile_dir,
        downloads_dir=staged_downloads_dir,
        url=url,
        destination=destination,
        headless=not headed,
        timeout_ms=timeout_ms,
        cooldown_ms=cooldown_ms,
        overwrite=overwrite,
    )

    print(f"Destination: {destination}")
    print(f"Downloaded: {len(report.downloaded)}")
    print(f"Skipped: {len(report.skipped)}")
    print(f"Failed: {len(report.failed)}")
    print(f"Manifest: {report.manifest_path}")
    return report.exit_code


def _run_verify_manifest(manifest_path: Path) -> int:
    verification = verify_download_manifest(manifest_path)
    print(f"Manifest: {manifest_path}")
    print(f"Expected files: {verification.expected_files}")
    print(f"Present files: {verification.present_files}")
    print(f"Missing files: {len(verification.missing_files)}")
    return verification.exit_code


def _run_retry_manifest(
    *,
    manifest_path: Path,
    headed: bool,
    timeout_ms: int,
    cooldown_ms: int,
    overwrite: str,
) -> int:
    repo_root = find_repo_root()
    profile_dir = browser_profile_dir(repo_root)

    if not profile_dir.exists():
        raise RuntimeError("Missing browser auth state. Run: uv run main auth")

    staged_downloads_dir = downloads_dir(repo_root)
    report = retry_missing_files_from_manifest(
        profile_dir=profile_dir,
        downloads_dir=staged_downloads_dir,
        manifest_path=manifest_path,
        headless=not headed,
        timeout_ms=timeout_ms,
        cooldown_ms=cooldown_ms,
        overwrite=overwrite,
    )
    print(f"Manifest: {report.manifest_path}")
    print(f"Retried downloads: {len(report.downloaded)}")
    print(f"Skipped: {len(report.skipped)}")
    print(f"Failed: {len(report.failed)}")
    return report.exit_code


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        if args.command == "auth":
            _run_auth(args.url)
            return 0
        if args.command == "browse":
            _run_browse(args.url)
            return 0
        if args.command == "download-folder":
            return _run_download_folder(
                url=args.url,
                destination=args.to,
                headed=args.headed,
                timeout_ms=args.timeout_ms,
                cooldown_ms=args.cooldown_ms,
                overwrite=args.overwrite,
            )
        if args.command == "verify-manifest":
            return _run_verify_manifest(args.manifest)
        if args.command == "retry-manifest":
            return _run_retry_manifest(
                manifest_path=args.manifest,
                headed=args.headed,
                timeout_ms=args.timeout_ms,
                cooldown_ms=args.cooldown_ms,
                overwrite=args.overwrite,
            )
    except RuntimeError as error:
        print(str(error), file=sys.stderr)
        return 2

    parser.error(f"Unsupported command: {args.command}")
    return 2
