import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

from idrive_backup_helper.browser.downloads.downloads import (
    download_current_folder,
    retry_missing_files_from_manifest,
    verify_download_manifest,
)
from idrive_backup_helper.browser.engine import DEFAULT_BROWSER_DEBUG_URL
from idrive_backup_helper.browser.session import (
    DEFAULT_BROWSE_URL,
    login_and_save_state,
    open_authenticated_browser,
)
from idrive_backup_helper.filesystem.paths import (
    browser_profile_dir,
    downloads_dir,
    find_repo_root,
)

DEFAULT_TIMEOUT_MS = 120 * 60 * 1_000


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="IDrive backup helper")
    subparsers = parser.add_subparsers(dest="command", required=True)

    auth_parser = subparsers.add_parser(
        "auth", help="Open a headed browser and cache IDrive login state"
    )
    auth_parser.add_argument(
        "--url",
        default="https://www.idrive.com/idrive/login/loginForm",
        help="IDrive URL to open for login",
    )
    auth_parser.add_argument(
        "--browser-debug-url",
        default=DEFAULT_BROWSER_DEBUG_URL,
        help="Chromium remote debugging URL for the persistent browser session",
    )

    browse_parser = subparsers.add_parser(
        "browse",
        help="Open an authenticated IDrive browser for manual folder inspection",
    )
    browse_parser.add_argument(
        "--url",
        default=DEFAULT_BROWSE_URL,
        help="IDrive URL to open in the authenticated browser",
    )
    browse_parser.add_argument(
        "--browser-debug-url",
        default=DEFAULT_BROWSER_DEBUG_URL,
        help="Chromium remote debugging URL for the persistent browser session",
    )

    download_parser = subparsers.add_parser(
        "download-folder",
        help="List visible files in one IDrive web folder (download step pending)",
    )
    download_parser.add_argument("--url", required=True, help="IDrive folder URL")
    download_parser.add_argument(
        "--to",
        required=True,
        type=Path,
        help="Local destination directory for downloaded files",
    )
    download_parser.add_argument(
        "--headed",
        action="store_true",
        help="Run browser in headed mode for debugging",
    )
    download_parser.add_argument(
        "--timeout-ms",
        type=int,
        default=DEFAULT_TIMEOUT_MS,
        help="Playwright timeout for page operations",
    )
    download_parser.add_argument(
        "--cooldown-ms",
        type=int,
        default=1_500,
        help="Pause between file download interactions",
    )
    download_parser.add_argument(
        "--overwrite",
        choices=["skip", "replace", "fail"],
        default="skip",
        help="How to handle already-existing destination files",
    )
    download_parser.add_argument(
        "--no-folder-cache",
        action="store_true",
        help="Disable cached folder listings and always re-scan folder contents",
    )
    download_parser.add_argument(
        "--no-resume-logs",
        action="store_true",
        help="Disable resume indexing from prior manifests for this URL/destination",
    )
    download_parser.add_argument(
        "--browser-debug-url",
        default=None,
        help=(
            "Attach to a persistent Chromium browser over CDP. "
            "Defaults to the local session when --headed is set."
        ),
    )

    verify_parser = subparsers.add_parser(
        "verify-manifest",
        help="Verify which files from a download manifest are still missing locally",
    )
    verify_parser.add_argument("--manifest", required=True, type=Path)

    retry_parser = subparsers.add_parser(
        "retry-manifest",
        help="Retry only missing files from a manifest generated by download-folder",
    )
    retry_parser.add_argument("--manifest", required=True, type=Path)
    retry_parser.add_argument("--headed", action="store_true")
    retry_parser.add_argument("--timeout-ms", type=int, default=DEFAULT_TIMEOUT_MS)
    retry_parser.add_argument("--cooldown-ms", type=int, default=1_500)
    retry_parser.add_argument(
        "--overwrite",
        choices=["skip", "replace", "fail"],
        default="replace",
    )
    retry_parser.add_argument(
        "--browser-debug-url",
        default=None,
        help=(
            "Attach to a persistent Chromium browser over CDP. "
            "Defaults to the local session when --headed is set."
        ),
    )

    return parser


def _run_auth(url: str, browser_debug_url: str) -> None:
    repo_root = find_repo_root()
    profile_dir = browser_profile_dir(repo_root)
    staged_downloads_dir = downloads_dir(repo_root)
    login_and_save_state(
        profile_dir=profile_dir,
        downloads_dir=staged_downloads_dir,
        start_url=url,
        browser_debug_url=browser_debug_url,
    )

    print(f"Opened persistent browser session at: {browser_debug_url}")
    print(f"Browser state path: {profile_dir}")
    print(
        "Next step: uv run main browse or uv run main download-folder --url <FOLDER_URL> --to <DEST_PATH>"
    )


def _run_browse(url: str, browser_debug_url: str) -> None:
    repo_root = find_repo_root()
    profile_dir = browser_profile_dir(repo_root)
    staged_downloads_dir = downloads_dir(repo_root)
    open_authenticated_browser(
        profile_dir=profile_dir,
        downloads_dir=staged_downloads_dir,
        start_url=url,
        browser_debug_url=browser_debug_url,
    )
    print(f"Opened persistent browser session at: {browser_debug_url}")


def _run_download_folder(
    *,
    url: str,
    destination: Path,
    headed: bool,
    timeout_ms: int,
    cooldown_ms: int,
    overwrite: str,
    browser_debug_url: str | None,
    no_folder_cache: bool,
    no_resume_logs: bool,
) -> int:
    repo_root = find_repo_root()
    profile_dir = browser_profile_dir(repo_root)
    effective_browser_debug_url = browser_debug_url
    if effective_browser_debug_url is None and headed:
        effective_browser_debug_url = DEFAULT_BROWSER_DEBUG_URL

    if not profile_dir.exists() and effective_browser_debug_url is None:
        raise RuntimeError("Missing browser auth state. Run: uv run main auth")

    staged_downloads_dir = downloads_dir(repo_root)
    effective_headless = not headed and effective_browser_debug_url is None

    report = download_current_folder(
        profile_dir=profile_dir,
        downloads_dir=staged_downloads_dir,
        url=url,
        destination=destination,
        headless=effective_headless,
        timeout_ms=timeout_ms,
        cooldown_ms=cooldown_ms,
        overwrite=overwrite,
        browser_debug_url=effective_browser_debug_url,
        use_folder_cache=not no_folder_cache,
        resume_from_logs=not no_resume_logs,
    )

    print(f"Destination: {destination}")
    print(f"Downloaded: {len(report.downloaded)}")
    print(f"Skipped: {len(report.skipped)}")
    print(f"Failed: {len(report.failed)}")
    if report.progress_log_path is not None:
        print(f"Progress log: {report.progress_log_path}")
    print(f"Manifest: {report.manifest_path}")
    return report.exit_code


def _run_verify_manifest(manifest_path: Path) -> int:
    verification = verify_download_manifest(manifest_path)
    print(f"Manifest: {manifest_path}")
    print(f"Expected files: {verification.expected_files}")
    print(f"Present files: {verification.present_files}")
    print(f"Missing files: {len(verification.missing_files)}")
    return verification.exit_code


def _run_retry_manifest(
    *,
    manifest_path: Path,
    headed: bool,
    timeout_ms: int,
    cooldown_ms: int,
    overwrite: str,
    browser_debug_url: str | None,
) -> int:
    repo_root = find_repo_root()
    profile_dir = browser_profile_dir(repo_root)
    effective_browser_debug_url = browser_debug_url
    if effective_browser_debug_url is None and headed:
        effective_browser_debug_url = DEFAULT_BROWSER_DEBUG_URL

    if not profile_dir.exists() and effective_browser_debug_url is None:
        raise RuntimeError("Missing browser auth state. Run: uv run main auth")

    staged_downloads_dir = downloads_dir(repo_root)
    effective_headless = not headed and effective_browser_debug_url is None

    report = retry_missing_files_from_manifest(
        profile_dir=profile_dir,
        downloads_dir=staged_downloads_dir,
        manifest_path=manifest_path,
        headless=effective_headless,
        timeout_ms=timeout_ms,
        cooldown_ms=cooldown_ms,
        overwrite=overwrite,
        browser_debug_url=effective_browser_debug_url,
    )
    print(f"Manifest: {report.manifest_path}")
    print(f"Retried downloads: {len(report.downloaded)}")
    print(f"Skipped: {len(report.skipped)}")
    print(f"Failed: {len(report.failed)}")
    if report.progress_log_path is not None:
        print(f"Progress log: {report.progress_log_path}")
    return report.exit_code


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        if args.command == "auth":
            _run_auth(args.url, args.browser_debug_url)
            return 0
        if args.command == "browse":
            _run_browse(args.url, args.browser_debug_url)
            return 0
        if args.command == "download-folder":
            return _run_download_folder(
                url=args.url,
                destination=args.to,
                headed=args.headed,
                timeout_ms=args.timeout_ms,
                cooldown_ms=args.cooldown_ms,
                overwrite=args.overwrite,
                browser_debug_url=args.browser_debug_url,
                no_folder_cache=args.no_folder_cache,
                no_resume_logs=args.no_resume_logs,
            )
        if args.command == "verify-manifest":
            return _run_verify_manifest(args.manifest)
        if args.command == "retry-manifest":
            return _run_retry_manifest(
                manifest_path=args.manifest,
                headed=args.headed,
                timeout_ms=args.timeout_ms,
                cooldown_ms=args.cooldown_ms,
                overwrite=args.overwrite,
                browser_debug_url=args.browser_debug_url,
            )
    except RuntimeError as error:
        print(str(error), file=sys.stderr)
        return 2

    parser.error(f"Unsupported command: {args.command}")
    return 2
